version: 2.1
#branches:
#  only:
#    - main
orbs:
  aws-cli: circleci/aws-cli@3.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: cimg/node:19.3.0
      - image: amazon/dynamodb-local
    steps:
      - checkout
      - run:
            name: Install Java
            command: 'sudo apt-get update && sudo apt-get install default-jre default-jdk'
      - run:
          name: Install AWS CLI
          command: 'sudo pip install awsebcli --upgrade'
#      - run:
#          name: Setup Container
#          command: |
#                  curl -k -L -o dynamodb-local.tgz http://dynamodb-local.s3-website-us-west-2.amazonaws.com/dynamodb_local_latest.tar.gz
#                  tar -xzf dynamodb-local.tgz
#                  java -D java.library.path=./DynamoDBLocal_lib -jar DynamoDBLocal.jar -sharedDb
#                background: true
      - run:
          name: Update Yarn
          command: 'yarn global add npm@latest'
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --immutable
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - .yarn/cache
            - .yarn/unplugged
      - run:
          name: Start Server
          command: 'yarn ci-start'
          background: true
      - run:
          name: Create Table
          command: 'yarn create-db'
      - run:
          name: Load Data
          command: 'yarn load-data'
      - run:
          name: Run Tests
          command: yarn run test