version: 2.1
orbs:
  aws-cli: circleci/aws-cli@3.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: cimg/node:19.3.0
    steps:
      - checkout
      - run:
            name: Install Java
            command: 'sudo apt-get update && sudo apt-get install default-jre default-jdk'
      - run:
          name: Update Yarn
          command: 'yarn global add npm@latest'
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --immutable
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - .yarn/cache
            - .yarn/unplugged
      - run:
          name: Run Tests
          command: yarn run test